version: 2.1

workflows:
  version: 2
  build: 
    jobs:
      - run_script:
          filters:
            branches:
              only:
                - master

jobs:
  run_script:
    docker:
      - image: circleci/node:10
        environment:
           CLOUDSDK_CORE_DISABLE_PROMPTS: 1
            CLOUDSDK_PYTHON_SITEPACKAGES: 1
    steps:
      - checkout
      - restore_cache:
          key: node-{{ checksum "package.json" }}            
      - restore_cache:
          key: gcsdk
      - run: 
          name: Install
          command: |
            sudo npm install -g npm@latest
            sudo npm install -g gulp
            npm install
            npm run clean
      - run: 
          name: Script
          command: |
            npm run build      
            gulp puppeteer:build
            npm run test
            node ./tools/travis/addCommitComment.js
      - save_cache:
          key: node-{{ checksum "package.json" }}            
          paths:
            - node_modules
      - save_cache:
          key: gcsdk
          paths:
            - home/circleci/google-cloud-sdk
      - run:
          name: After Success
          command: |
            ./tools/travis/deploy-master.sh
            ./tools/travis/deploy-pr.sh
            ./tools/travis/flush-memcache.sh
            node ./tools/travis/removeStagedPRs.js
