version: 2.1

workflows:
  version: 2
  build: 
    jobs:
      - reload_cache:
        filters:
          branches:
            only:
              - master
      - install:
        filters:
          branches:
            only:
              - master
      - run_script:
        filters:
          branches:
            only:
              - master
      - on_success:
        requires:
          - reload_cache
          - install
          - run_script
        filters:
          branches:
            only:
              - master

jobs:
  reload_cache:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - node_modules
      - "$HOME/google-cloud-sdk"
  install:
    docker:
      - image: circleci/node:10
    steps:
      - npm install
      - npm run clean
  run_script:
    docker:
      - image: circleci/node:10
    steps:
      - npm run build
      - gulp puppeteer:build
      - npm run test
      - node ./tools/travis/removeStagedPRs.js
  on_success:
    docker:
      - image: circleci/node:10
    steps:
      - ./tools/travis/deploy-master.sh
      - ./tools/travis/deploy-pr.sh
      - ./tools/travis/flush-memcache.sh
      - node ./tools/travis/removeStagedPRs.js
