version: 2.1

workflows:
  version: 2
  build: 
    jobs:
      - run_script:
        filters:
          branches:
            only:
              - master
      - on_success:
        filters:
          branches:
            only:
              - master

jobs:
  run_script:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - npm run clean
      - npm run build
      - gulp puppeteer:build
      - npm run test
      - node ./tools/travis/removeStagedPRs.js
  on_success:
    docker:
      - image: circleci/node:10
    steps:
      - ./tools/travis/deploy-master.sh
      - ./tools/travis/deploy-pr.sh
      - ./tools/travis/flush-memcache.sh
      - node ./tools/travis/removeStagedPRs.js
