version: 2.1

workflows:
  version: 2
  build: 
    jobs:
      - run_script:
        filters:
          branches:
            only:
              - master

jobs:
  run_script:
    docker:
      - image: circleci/node:10
    steps:
      - restore_cache:
        key: dependencies
      - run: 
        name: npm update
        command: 'sudo npm install -g npm@latest'
      - run: 
        name: install dependencies
        command: npm install
      - save_cache:
        key: dependencies
        paths:
          - node_modules
          - "$HOME/google-cloud-sdk/"
      - run: npm run clean
      - run: npm run build
      - run: npm install -g gulp
      - run: gulp --version
      - run: gulp puppeteer:build
      - run: npm run test
      - run: node ./tools/travis/addCommitComment.js
      
