version: 2.1

workflows:
  version: 2
  build: 
    jobs:
      - run_script:
        filters:
          branches:
            only:
              - master
      - on_success:
        requires:
            - run_script
        filters:
          branches:
            only:
              - master

jobs:
  run_script:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: 'sudo npm install -g npm@latest'
      - run: npm install
      - run: npm run clean
      - run: npm run build
      - run: 'sudo npm install -g gulp'
      - run: gulp puppeteer:build
      - run: npm run test
      - run: node ./tools/travis/addCommitComment.js

  on_success:
    docker:
      - image: circleci/node:10
    steps:
      - run: ./tools/travis/deploy-master.sh
      - run: ./tools/travis/deploy-pr.sh
      - run: ./tools/travis/flush-memcache.sh
      - run: node ./tools/travis/removeStagedPRs.js
